import type { Metadata } from "next";
import { nunito_sans } from "./ui/fonts";

import "./globals.css";
import Providers from "./providers/providers";
import Header from "./ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito_sans.className} antialiased min-h-screen bg-lightGrayBg dark:bg-darkBlueBg`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
