import type { Metadata } from "next";
import { nunito_sans } from "./ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito_sans.className} antialiased min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
